workshop_10_14/core/urls.py
from django.urls import path
from core.views import (
    about_view,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    ProductListView,
    generate_random_product_view
)

app_name = "core"

urlpatterns = [
    path("", ProductListView.as_view(), name="home"),
    path("about/", about_view, name="about"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product-details"),
    path("products/create/", ProductCreateView.as_view(), name="product-create"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product-update"),
    path("products/<int:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"),
    path("products/generate/", generate_random_product_view, name="generate-random-product"),
]

workshop_10_14/users/urls.py
from django.urls import path
from users.views import LoginView, LogoutView, RegisterUser

app_name = "users"

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", RegisterUser.as_view(), name="register"),
]

workshop_10_14/workshop_10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("users.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workshop_10_14/blog/models.py
from django.db import models

# Create your models here.

workshop_10_14/core/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from users.models import User



class Product(models.Model):
    thumbnail = models.ImageField(upload_to="products/", blank=True, null=True)
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.DecimalField(
        default=0.00,
        max_digits=5,
        decimal_places=2,
        validators=[MinValueValidator(0.00), MaxValueValidator(100.00)]
    )
    stock = models.PositiveIntegerField(default=0)
    is_active = models.BooleanField(default=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def discounted_price(self):
        return round(self.price - (self.price * self.discount / 100), 2)

    def rating(self):
        reviews = self.review_set.all()
        if reviews:
            return sum([review.rating for review in reviews]) / len(reviews)
        return 0.0

    def get_stars(self):
        half_star = '<i class="bi bi-star-half text-warning"></i>' * (self.rating() % 1 > 0)
        full_stars = '<i class="bi bi-star-fill text-warning"></i>' * int(self.rating())
        if half_star:
            return full_stars + half_star + '<i class="bi bi-star text-warning"></i>' * (5 - int(self.rating()) - 1)

        return full_stars +  '<i class="bi bi-star text-warning"></i>' * (5 - int(self.rating()))


class Review(models.Model):
    class Meta:
        unique_together = ["user", "product"]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    comment = models.TextField(blank=True, null=True)

workshop_10_14/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

workshop_10_14/users/forms.py
from django.contrib.auth.forms import UserCreationForm as DjangoUserCreationForm
from users.models import User


class UserCreationForm(DjangoUserCreationForm):
    class Meta(DjangoUserCreationForm.Meta):
        model = User

workshop_10_14/blog/views.py
from django.shortcuts import render

# Create your views here.

workshop_10_14/core/views.py
import random
from string import ascii_lowercase

from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
    ListView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from core.models import Product

@login_required
def home_view(request):
    return render(
        request,
        "index.html",
        {
            "products": Product.objects.all()
        }
    )

@login_required
def about_view(request):
    return render(request, "about.html")

# @login_required
# def product_details_view(request, pk):
#     product = Product.objects.get(pk=pk)
#     return render(request, "core/product_details.html", {
#         "product": product
#     })

@login_required
def generate_random_product_view(request):
    Product.objects.create(
        thumbnail="/products/samsung-galaxy-s25-ultra-titanium-silver-blue.webp",
        name="".join(random.choices(ascii_lowercase, k=20)),
        description="".join(random.choices(ascii_lowercase, k=100)),
        price=random.randint(10, 2000),
        discount=random.randint(0, 100),
        stock=random.randint(0, 100),
    )

    return redirect("core:home")


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "core/product_details.html"


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    fields = "__all__"
    template_name = "core/product_create.html"

    def get_success_url(self):
        return reverse("core:product-details", kwargs={"pk": self.object.pk})


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    fields = "__all__"
    template_name = "core/product_update.html"

    def get_success_url(self):
        return reverse("core:product-details", kwargs={"pk": self.object.pk})


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = "core/product_delete.html"
    success_url = reverse_lazy("core:home")


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = "index.html"
    context_object_name = "products"
    paginate_by = 6
    ordering = ["-created_at"]
    search_fields = ["name"]

    def get_queryset(self):
        return super().get_queryset().filter(name__icontains=self.request.GET.get("search", ""))

workshop_10_14/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView as DjangoLoginView, LogoutView as DjangoLogoutView
from django.views.generic import CreateView
from users.models import User
from users.forms import UserCreationForm


class LoginView(DjangoLoginView):
    template_name = "users/login.html"
    next_page = "/"
    redirect_authenticated_user = True


class LogoutView(DjangoLogoutView):
    next_page = reverse_lazy("users:login")


class RegisterUser(CreateView):
    template_name = "users/register.html"
    success_url = reverse_lazy("users:login")
    form_class = UserCreationForm
    model = User

workshop_10_14/templates/about.html
{% extends "base.html" %}
{% block title %}About Page{% endblock  %}
{% block content %}
    <h1>About page</h1>
{% endblock %}
    

workshop_10_14/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=viewport, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

    <style>
        body {
            max-width: 100vw !important;
            overflow-x: hidden;
        }
        .product {
            transition: 0.3s ease-in-out;
            cursor: pointer;
        }
        .tags {
            transition: 0.3s ease-in-out;

        }

        .product:hover {
            transform: scale(1.05);
            box-shadow: 0px 0px 20px 0 rgb(66, 48, 232) !important;
        }
        .product:hover .tags {
            opacity: 1 !important;
        }
    </style>
</head>
<body>

    {% include "components/nav.html" %}

    {% block content %}
    {% endblock %}
    
</body>
</html>

workshop_10_14/templates/components/nav.html
<nav>
    {% if user.is_authenticated %}
    <ul>
        Hello, {{ user.username }}
        <li><a href="/">Home</a></li>
        <li><a href="/about/">About</a></li>
        <li>
            <form method="POST" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Log out</button>
            </form>
        </li>
    </ul>
    {% else %}
    <ul>
        <li><a href="{% url 'users:login' %}">Login</a></li>
        <li><a href="/users/register/">Register</a></li>
    </ul>

    {% endif %}
</nav>

workshop_10_14/templates/core/product_create.html
{% extends "base.html" %}

{% block title %}
    Add Product
{% endblock %}

{% block content %}
<div class="container">

    <h3>Add Product</h3>
    <form enctype="multipart/form-data" class="border p-3 rounded shadow bg-dark text-light" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        
        <!-- Submit button -->
        <button type="submit" data-mdb-button-init data-mdb-ripple-init 
        class="btn btn-primary btn-block mb-4 w-100">Add new Product</button>
    </form>
</div>
{% endblock %}

workshop_10_14/templates/core/product_delete.html
{% extends "base.html" %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
<div class="container">
    <form enctype="multipart/form-data" class="border p-3 rounded shadow bg-dark text-light" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        <p>Are you sure you want to delete "{{ product.name }}"?</p>
        <!-- Submit button -->
        <button type="submit" data-mdb-button-init data-mdb-ripple-init 
        class="btn btn-outline-danger btn-block mb-4 w-100">Delete</button>
        <a href="{% url 'core:product-details' product.id %}" class="btn btn-primary btn-block mb-4 w-100">Cancel</a>
    </form>
</div>
{% endblock %}

workshop_10_14/templates/core/product_details.html
{% extends "base.html" %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
<div class="container mt-5">
    <a class="btn btn-warning" href="{% url 'core:product-update' product.pk %}">Update</a>
    <a class="btn btn-danger" href="{% url 'core:product-delete' product.pk %}">Delete</a>
    
    <div class="row border rounded shadow p-2">
        <!-- Product Images -->
        <div class="col-md-6 mb-4">
            <img src="{{ product.thumbnail.url }}" alt="Product" class="img-fluid rounded mb-3 product-image" id="mainImage">

        </div>

        <!-- Product Details -->
        <div class="col-md-6">
            <h2 class="mb-3">{{ product.name }}</h2>
            <div class="mb-3">
                <span class="h4 me-2">${{ product.price }}</span>
                {% comment %} <span class="text-muted"><s>$399.99</s></span> {% endcomment %}
            </div>
            <div class="mb-3">
                {{ product.get_stars|safe }}
                <span class="ms-2">{{ product.rating }} ({{ product.review_set.count }} reviews)</span>
            </div>
            <p class="mb-4">{{ product.description }}</p>

            <div class="mb-4">
                <label for="quantity" class="form-label">Quantity:</label>
                <input type="number" class="form-control" id="quantity" value="1" min="1" style="width: 80px;">
            </div>
            <button class="btn btn-primary btn-lg mb-3 me-2">
                    <i class="bi bi-cart-plus"></i> Add to Cart
                </button>
            <button class="btn btn-outline-secondary btn-lg mb-3">
                    <i class="bi bi-heart"></i> Add to Wishlist
                </button>

        </div>
    </div>
    {% for review in product.review_set.all %}
        <div class="row border rounded shadow p-2 mt-4">
            <div class="col-md-6">
                <h5>{{ review.user.username }}</h5>
                <p>{{ review.comment }}</p>
            </div>
            <div class="col-md-6">
                <p class="text-muted">Rating: {{ review.rating }}</p>

            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

workshop_10_14/templates/core/product_update.html
{% extends "base.html" %}

{% block title %}
    {{ product.name }}
{% endblock %}

{% block content %}
<div class="container">

    <h3>Update {{ product.name }}</h3>
    <form enctype="multipart/form-data" class="border p-3 rounded shadow bg-dark text-light" method="POST">
        {% csrf_token %}
        {{ form.as_p}}
        
        <!-- Submit button -->
        <button type="submit" data-mdb-button-init data-mdb-ripple-init 
        class="btn btn-primary btn-block mb-4 w-100">Save</button>
        <a href="{% url 'core:product-details' product.id %}" class="btn btn-outline-secondary btn-block mb-4 w-100">Cancel</a>
    </form>
</div>
{% endblock %}

workshop_10_14/templates/index.html
{% extends "base.html" %}

{% block title %}
    Home Page
{% endblock %}

{% block content %}
<div class="container">

    <h1>Welcome to my page</h1>
    <form class="d-flex gap-1 justify-content-center mb-3" method="GET">
        <input class="form-control" type="text" name="search" placeholder="Search..." value="{{ request.GET.search }}"> 
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
    <a class="btn btn-primary" href="{% url 'core:product-create' %}">Add new Product</a>
    <a class="btn btn-primary" href="{% url 'core:generate-random-product' %}">Generate Random Product</a>

    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-6 g-4 p-4">
    {% for product in products %}
    <div class="col">
        <div class="card h-100 shadow-sm">
            <a href="/products/{{ product.id }}/">
                <img src="{{ product.thumbnail.url }}" class="card-img-top" alt="Product 4">
            </a>
            <div class="card-body">
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">
                    <span class="badge bg-primary">{{ product.created_at }}</span>
                    {{ product.description|truncatechars:30 }}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    {% if product.discount %}
                        <div class="d-flex flex-column">
                            <span class="text-muted text-decoration-line-through">
                                ${{ product.price }}
                            </span>
                            <span class="h5 mb-0">${{ product.discounted_price }}</span>
                            <span class="badge bg-danger">-{{ product.discount }}%</span>
                        </div>
                    {% else %}
                        <span class="h5 mb-0">${{ product.price }}</span>
                    {% endif %}
                    <button class="btn btn-outline-primary"><i class="bi bi-cart-plus"></i> Add to Cart</button>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    </div>

    <div class="d-flex justify-content-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a class="btn btn-primary"  href="?page=1&search={{ request.GET.search }}">&laquo; first</a>
                <a class="btn btn-primary"  href="?page={{ page_obj.previous_page_number }}&search={{ request.GET.search }}">previous</a>
            {% endif %}
    
            <span class="btn btn-primary disabled">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a  class="btn btn-primary" href="?page={{ page_obj.next_page_number }}&search={{ request.GET.search }}">next</a>
                <a  class="btn btn-primary" href="?page={{ page_obj.paginator.num_pages }}&search={{ request.GET.search }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

workshop_10_14/templates/users/login.html
{% extends "base.html" %}

{% block title %}
    Login
{% endblock %}

{% block content %}
<div class="container">

<form class="border p-3 rounded shadow bg-dark text-light" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    
    <!-- Submit button -->
    <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4 w-100">Sign in</button>
  
    <!-- Register buttons -->
    <div class="text-center">
      <p>Not a member? <a href="{% url 'users:register' %}">Register</a></p>
    </div>
  </form>
</div>
{% endblock %}

workshop_10_14/templates/users/register.html
{% extends "base.html" %}

{% block title %}
    Sign Up
{% endblock %}

{% block content %}
<div class="container">

<form class="border p-3 rounded shadow bg-dark text-light" method="POST">
    {% csrf_token %}
    {{ form.as_p}}
    
    <!-- Submit button -->
    <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4 w-100">Sign up</button>
  
    <!-- Register buttons -->
    <div class="text-center">
      <p>Already a member? <a href="{% url 'users:login' %}">Login</a></p>
    </div>
  </form>
</div>
{% endblock %}